### ISSUE TITLE
failure during git-to-dbs with lucene-bo in place

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lucene-bo#2]
git-to-dbs transferred 2538 person graphs and then terminated with the following error:

```
$ time java -jar target/gittodbs-0.7.jar -fuseki -transferOnto -transferAllDB -timeout 60 -progress -gitDir ../bdrc-gits/
[main] INFO git2dbs - connecting to fuseki on http://localhost:13180/fuseki/bdrcrw/data
sending all person files to Fuseki
[main] ERROR git2dbs - execution error during putModel of http://purl.bdrc.io/resource/P9412, this shouldn't happen, quitting...
java.util.concurrent.ExecutionException: org.apache.jena.atlas.web.HttpException: 500 - Internal Server Error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at io.bdrc.gittodbs.FusekiHelpers.callFuseki(FusekiHelpers.java:110)
	at io.bdrc.gittodbs.FusekiHelpers.transferModel(FusekiHelpers.java:123)
	at io.bdrc.gittodbs.TransferHelpers.addFileFuseki(TransferHelpers.java:197)
	at io.bdrc.gittodbs.TransferHelpers.syncTypeFuseki(TransferHelpers.java:216)
	at io.bdrc.gittodbs.TransferHelpers.syncType(TransferHelpers.java:143)
	at io.bdrc.gittodbs.TransferHelpers.sync(TransferHelpers.java:130)
	at io.bdrc.gittodbs.GitToDB.main(GitToDB.java:166)
Caused by: org.apache.jena.atlas.web.HttpException: 500 - Internal Server Error
	at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1084)
	at org.apache.jena.riot.web.HttpOp.execHttpPut(HttpOp.java:965)
	at org.apache.jena.web.DatasetGraphAccessorHTTP.doPut(DatasetGraphAccessorHTTP.java:158)
	at org.apache.jena.web.DatasetGraphAccessorHTTP.httpPut(DatasetGraphAccessorHTTP.java:153)
	at org.apache.jena.web.DatasetAdapter.putModel(DatasetAdapter.java:70)
	at io.bdrc.gittodbs.FusekiHelpers$1.call(FusekiHelpers.java:97)
	at io.bdrc.gittodbs.FusekiHelpers$1.call(FusekiHelpers.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

real	1m54.594s
user	0m11.319s
sys	0m1.356s
```

The catalina.out and localhost logs didn't seem to show anything other than a really large amount of ewts-converter output, but nothing just before the error in git-to-dbs:

[log-extract.txt.zip](https://github.com/BuddhistDigitalResourceCenter/lucene-bo/files/1319357/log-extract.txt.zip)

The git-to-dbs error report above does indicate that P9412 is the record where the failure occurred. It looks unremarkable, but is included:

[P9412.ttl.zip](https://github.com/BuddhistDigitalResourceCenter/lucene-bo/files/1319348/P9412.ttl.zip)

The same set of files (146K) was successfully transferred in entirety with the same configuration using Lucene Standard Analyzer with default constructor so the difference appears to be reasonably attributable to lucene-bo.

Since there were 2538 graphs transferred before the error it seems likely a data dependent error in the lucene-bo analyzer - but I may be overthinking it.

**Comment by eroux** [comment]
Should be fixed in 1.1!
